<a href="https://colab.research.google.com/github/iskra3138/test/blob/master/brambox_steelcount.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files
uploaded = files.upload()

Saving train.pkl to train.pkl


In [1]:
ls

sample_data/  train.pkl


In [2]:
!pip install brambox

# brambox 사용법 : https://eavise.gitlab.io/brambox/notes/02-getting_started.html
# brambox load option : https://eavise.gitlab.io/brambox/api/io-formats.html

In [0]:
# Basic imports
import brambox as bb
import numpy as np
import pandas as pd
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns

# Settings
sns.set(style='darkgrid', context='notebook')  # Nicer plotting colors
bb.logger.setConsoleLevel('ERROR')             # Only show error log messages

In [0]:
train_data = bb.io.load('anno_pickle', 'train.pkl')

In [5]:
display(train_data.head())

image  ... ignore
0  ./data/split_train_dataset/0009496A/0009496A_s...  ...  False
1  ./data/split_train_dataset/0009496A/0009496A_s...  ...  False
2  ./data/split_train_dataset/0009496A/0009496A_s...  ...  False
3  ./data/split_train_dataset/0009496A/0009496A_s...  ...  False
4  ./data/split_train_dataset/0009496A/0009496A_s...  ...  False

[5 rows x 12 columns]

In [6]:
train_data

image  ... ignore
0       ./data/split_train_dataset/0009496A/0009496A_s...  ...  False
1       ./data/split_train_dataset/0009496A/0009496A_s...  ...  False
2       ./data/split_train_dataset/0009496A/0009496A_s...  ...  False
3       ./data/split_train_dataset/0009496A/0009496A_s...  ...  False
4       ./data/split_train_dataset/0009496A/0009496A_s...  ...  False
...                                                   ...  ...    ...
146214              ./data/train_dataset_mix/_mix1499.jpg  ...  False
146215              ./data/train_dataset_mix/_mix1499.jpg  ...  False
146216              ./data/train_dataset_mix/_mix1499.jpg  ...  False
146217              ./data/train_dataset_mix/_mix1499.jpg  ...  False
146218              ./data/train_dataset_mix/_mix1499.jpg  ...  False

[146219 rows x 12 columns]

In [7]:
class_label = (train_data['class_label'])
class_label.unique()

array(['steel'], dtype=object)

In [8]:
id = (train_data['id'])
id.unique()

array([0])

In [9]:
lost = (train_data['lost'])
lost.unique()

array([None], dtype=object)

In [10]:
difficult = (train_data['difficult'])
difficult.unique()

array([False])

In [11]:
ignore = (train_data['ignore'])
ignore.unique()

array([False])

In [12]:
image = (train_data['image'])
image.unique()

[./data/split_train_dataset/0009496A/0009496A_s..., ./data/split_train_dataset/0009496A/0009496A_s..., ./data/split_train_dataset/0009496A/0009496A_s..., ./data/split_train_dataset/0009496A/0009496A_s..., ./data/split_train_dataset/0009496A/0009496A_s..., ..., ./data/train_dataset_mix/_mix1493.jpg, ./data/train_dataset_mix/_mix1495.jpg, ./data/train_dataset_mix/_mix1496.jpg, ./data/train_dataset_mix/_mix1498.jpg, ./data/train_dataset_mix/_mix1499.jpg]
Length: 3941
Categories (3941, object): [./data/split_train_dataset/0009496A/0009496A_s..., ./data/split_train_dataset/0009496A/0009496A_s...,
                            ./data/split_train_dataset/0009496A/0009496A_s..., ./data/split_train_dataset/0009496A/0009496A_s...,
                            ..., ./data/train_dataset_mix/_mix1495.jpg,
                            ./data/train_dataset_mix/_mix1496.jpg, ./data/train_dataset_mix/_mix1498.jpg,
                            ./data/train_dataset_mix/_mix1499.jpg]