<a href="https://colab.research.google.com/github/iskra3138/colab_repo/blob/master/convert_dtype_%26_resize.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%tensorflow_version 2.x

TensorFlow 2.x selected.


In [0]:
import tensorflow as tf

In [3]:
!wget https://www.c-ville.com/wp-content/uploads/2019/09/Cats-660x335.jpg

--2020-02-12 07:35:14--  https://www.c-ville.com/wp-content/uploads/2019/09/Cats-660x335.jpg
Resolving www.c-ville.com (www.c-ville.com)... 104.196.149.76
Connecting to www.c-ville.com (www.c-ville.com)|104.196.149.76|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38807 (38K) [image/jpeg]
Saving to: ‘Cats-660x335.jpg.1’

Cats-660x335.jpg.1  100%[===================>]  37.90K  --.-KB/s    in 0.01s   

2020-02-12 07:35:14 (3.01 MB/s) - ‘Cats-660x335.jpg.1’ saved [38807/38807]



In [4]:
## resize -> convert_image_dtype 순일 때는 [0,1) 사이로 안 바뀜. 즉 convert_image_dtype이 안 먹음
image = tf.io.read_file('Cats-660x335.jpg')
image = tf.image.decode_jpeg(image)
image = tf.image.resize(image, [224,224])
image = tf.image.convert_image_dtype(image, tf.float32)
print (image.numpy())

[[[254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]
  ...
  [254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]]

 [[254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]
  ...
  [254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]]

 [[254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]
  ...
  [254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]]

 ...

 [[254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]
  ...
  [254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]]

 [[254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]
  ...
  [254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]]

 [[254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]
  ...
  [254. 254. 254.]
  [254. 254. 254.]
  [254. 254. 254.]]]


In [5]:
## convert_image_dtype -> resize 순일 때는 [0,1) 사이로 바뀜. 즉 convert_image_dtype이 먹었음
image = tf.io.read_file('Cats-660x335.jpg')
image = tf.image.decode_jpeg(image)
image = tf.image.convert_image_dtype(image, tf.float32)
image = tf.image.resize(image, [224,224])

print (image.numpy())

[[[0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  ...
  [0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]]

 [[0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  ...
  [0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]]

 [[0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  ...
  [0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]]

 ...

 [[0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  ...
  [0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]]

 [[0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  [0.9960785 0.9960785 0.9960785]
  ...
  [0.9960785 0.9960785 0.9960785]
  [0