<a href="https://colab.research.google.com/github/iskra3138/colab_repo/blob/master/TF_padding_option.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# TF padding opition 계산 식

## SAME: out_size = ceil(float(in_size) / float(stride)
## VALID: out_size = ceil(float(in_size - filter_size + 1) / float(stride))

In [2]:
import tensorflow as tf
import math

# stride가 1일 때

In [3]:
# input = tf.constant([[1, 2, 3, 4]])
in_size = 4
stride = 1

# VALID: out_size  = ceil(float(in_size - filter_size + 1) / float(stride))
valid_out_k2_s1 = math.ceil(float(in_size - 2 + 1 ) / float(stride))
valid_out_k3_s1 = math.ceil(float(in_size - 3 + 1 ) / float(stride))
print ('VALID, in: {}, filter: 2, stride: {} ---> out_size: {}'.format(in_size, stride, valid_out_k2_s1))
print ('VALID, in: {}, filter: 3, stride: {} ---> out_size: {}'.format(in_size, stride, valid_out_k3_s1))
print ()
# SAME: out_size = ceil(float(in_size) / float(stride)
same_out_s1 = math.ceil(float(in_size) / float(stride))
print ('SAME, in: {}, stride: {} ---> out_size: {}'.format(in_size, stride, same_out_s1))

VALID, in: 4, filter: 2, stride: 1 ---> out_size: 3
VALID, in: 4, filter: 3, stride: 1 ---> out_size: 2

SAME, in: 4, stride: 1 ---> out_size: 4


In [4]:
## stride = 1 일 때,
stride = 1

x = tf.constant([[1, 2, 3, 4]])
x = tf.reshape(x, [1, 4, 1, 1])  # give a shape accepted by tf.nn.max_pool

# padding option이 VALID 이면, padding 없음
with tf.Session() as sess:
  valid_pad_k2_s1 = tf.nn.max_pool(x, [1,2,1,1], [1,stride,1,1], padding='VALID', name='valid_pad_k2_s1') ## padding [1, 2, 3, 4] ## output [2, 3, 4]
  valid_pad_k3_s1 = tf.nn.max_pool(x, [1,3,1,1], [1,stride,1,1], padding='VALID', name='valid_pad_k3_s1') ## padding [1, 2, 3, 4] ## output [3, 4]

  print (sess.run(valid_pad_k2_s1).reshape(valid_out_k2_s1))
  print (sess.run(valid_pad_k3_s1).reshape(valid_out_k3_s1), '\n')

## padding option이 SAME 이면, output이 same_out 값 '4' 가 되도록 적절한 padding 추가
#### 홀수개 필요 시 오른쪽/아래에 추가 배분
#### 짝수개 필요시 양쪽에 배분
with tf.Session() as sess:
  same_pad_k2_s1 = tf.nn.max_pool(x, [1,2,1,1], [1,stride,1,1], padding='SAME') ## padding [1, 2, 3, 4, 0] ## output [2, 3, 4, 4]
  same_pad_k3_s1 = tf.nn.max_pool(x, [1,3,1,1], [1,stride,1,1], padding='SAME') ## padding [0, 1, 2, 3, 4, 0] ## output [2, 3, 4, 4]
  same_pad_k4_s1 = tf.nn.max_pool(x, [1,4,1,1], [1,stride,1,1], padding='SAME') ## padding [0, 1, 2, 3, 4, 0, 0] ## output [3, 4, 4, 4]
  same_pad_k5_s1 = tf.nn.max_pool(x, [1,5,1,1], [1,stride,1,1], padding='SAME') ## padding [0, 0, 1, 2, 3, 4, 0, 0] ## output [3, 4, 4, 4]

  print (sess.run(same_pad_k2_s1).reshape(same_out_s1))
  print (sess.run(same_pad_k3_s1).reshape(same_out_s1))
  print (sess.run(same_pad_k4_s1).reshape(same_out_s1))
  print (sess.run(same_pad_k5_s1).reshape(same_out_s1))

[2 3 4]
[3 4] 

[2 3 4 4]
[2 3 4 4]
[3 4 4 4]
[3 4 4 4]


# stride가 2일 때

In [5]:
# input = tf.constant([[1, 2, 3, 4]])
in_size = 4
stride = 2

# VALID: out_size  = ceil(float(in_size - filter_size + 1) / float(stride))
valid_out_k2_s2 = math.ceil(float(in_size - 2 + 1 ) / float(stride))
valid_out_k3_s2 = math.ceil(float(in_size - 3 + 1 ) / float(stride))
print ('VALID, in: {}, filter: 2, stride: {} ---> out_size: {}'.format(in_size, stride, valid_out_k2_s2))
print ('VALID, in: {}, filter: 3, stride: {} ---> out_size: {}'.format(in_size, stride, valid_out_k3_s2))
print ()
# SAME: out_size = ceil(float(in_size) / float(stride)
same_out_s2 = math.ceil(float(in_size) / float(stride))
print ('SAME, in: {}, stride: {} ---> out_size: {}'.format(in_size, stride, same_out_s2))

VALID, in: 4, filter: 2, stride: 2 ---> out_size: 2
VALID, in: 4, filter: 3, stride: 2 ---> out_size: 1

SAME, in: 4, stride: 2 ---> out_size: 2


In [6]:
## stride = 2 일 때,
stride = 2

x = tf.constant([[1, 2, 3, 4]])
x = tf.reshape(x, [1, 4, 1, 1])  # give a shape accepted by tf.nn.max_pool

# padding option이 VALID 이면, padding 없음
with tf.Session() as sess:
  valid_pad_k2 = tf.nn.max_pool(x, [1,2,1,1], [1,stride,1,1], padding='VALID') ## padding [1, 2, 3, 4] ## output [2, 4]
  valid_pad_k3 = tf.nn.max_pool(x, [1,3,1,1], [1,stride,1,1], padding='VALID') ## padding [1, 2, 3, 4] ## output [3]

  print (sess.run(valid_pad_k2).reshape(valid_out_k2_s2))
  print (sess.run(valid_pad_k3).reshape(valid_out_k3_s2), '\n')

## padding option이 SAME 이면, output이 same_out 값 '2' 가 되도록 적절한 padding 추가
#### 홀수개 필요 시 오른쪽/아래에 추가 배분
#### 짝수개 필요시 양쪽에 배분
with tf.Session() as sess:
  same_pad_k2 = tf.nn.max_pool(x, [1,2,1,1], [1,stride,1,1], padding='SAME') ## padding [1, 2, 3, 4] ## output [2, 4]
  same_pad_k3 = tf.nn.max_pool(x, [1,3,1,1], [1,stride,1,1], padding='SAME') ## padding [1, 2, 3, 4, 0] ## output [3, 4]
  same_pad_k4 = tf.nn.max_pool(x, [1,4,1,1], [1,stride,1,1], padding='SAME') ## padding [0, 1, 2, 3, 4, 0] ## output [3, 4]
  same_pad_k5 = tf.nn.max_pool(x, [1,5,1,1], [1,stride,1,1], padding='SAME') ## padding [0, 1, 2, 3, 4, 0, 0] ## output [4, 4]
  same_pad_k6 = tf.nn.max_pool(x, [1,6,1,1], [1,stride,1,1], padding='SAME') ## padding [0, 0, 1, 2, 3, 4, 0, 0] ## output [4, 4]

  print (sess.run(same_pad_k2).reshape(same_out_s2))
  print (sess.run(same_pad_k3).reshape(same_out_s2))
  print (sess.run(same_pad_k4).reshape(same_out_s2))
  print (sess.run(same_pad_k5).reshape(same_out_s2))
  print (sess.run(same_pad_k6).reshape(same_out_s2))

[2 4]
[3] 

[2 4]
[3 4]
[3 4]
[4 4]
[4 4]
